#Updated at 2025-05-13 18:18:59
#Tue May 13 18:18:59 CST 2025
buadRate=9600
callbackHookEnabledFlag=true
callbackHookUrl=http\://localhost\:8888/serial-tool/callback
functionType=03 Holding Register (4x)
intervalSeconds=2
listeningAddress=1
portName=COM2
slaveId=1
