#Updated at 2025-05-14 14:53:24
#Wed May 14 14:53:24 CST 2025
buadRate=9600
callbackHookEnabledFlag=true
callbackHookUrl=http\://localhost\:8888/serial-tool/callback
dataType=TWO_BYTE_INT_SIGNED
functionType=03 Holding Register (4x)
intervalSeconds=3
listeningAddress=1
portName=COM2
slaveId=1
